## Alzheimer_Disease_Prediction

This notebook demonstrates logistic regression model using alzheimer disease gene expression dataset

In [ ]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from google.colab import drive
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
# Import necessary libraries
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

### Mount Google Drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


### Load the Dataset

In [ ]:
# Load the dataset
ad_data = pd.read_csv('/content/drive/MyDrive/PERSONAL/Biomedical/alzheimer disease.csv')

# Display the first few rows of the dataset
ad_data.head()

ID  Background  Precentral_L  Precentral_R  Frontal_Sup_2_L  \
0  ADCTL001    0.007495      0.262134      0.203567         0.258888   
1  ADCTL002    0.009005      0.249045      0.209544         0.280683   
2  ADCTL003    0.009042      0.258154      0.218058         0.305928   
3  ADCTL004    0.007839      0.266917      0.237448         0.264880   
4  ADCTL005    0.009090      0.282655      0.249729         0.340169   

   Frontal_Sup_2_R  Frontal_Mid_2_L  Frontal_Mid_2_R  Frontal_Inf_Oper_L  \
0         0.261755         0.320331         0.272735            0.316372   
1         0.264050         0.300900         0.266972            0.286501   
2         0.292087         0.367378         0.307326            0.335420   
3         0.266480         0.322434         0.247450            0.270734   
4         0.320847         0.389368         0.316534            0.348195   

   Frontal_Inf_Oper_R  ...     UQCRHL      UQCRQ      UTP6       VCAN  \
0            0.289429  ...   9.595161   8.900996  8.173745  10.101391   
1            0.249771  ...  10.309510  10.387745  7.607429  10.867843   
2            0.279548  ...   9.109219   9.588959  8.157013  10.492056   
3            0.272055  ...   8.705610   8.929866  7.750466   9.769650   
4            0.300438  ...   9.052294   8.773474  7.707519  10.567930   

       ZMAT2    ZNF281     ZNF467    ZNHIT3     ZZEF1  Label  
0   9.733100  8.917093   9.391262  8.406436  7.943020     AD  
1  10.900267  9.512067   9.399022  9.641627  7.202653     AD  
2   9.296857  9.646761  10.267368  8.631247  8.053132     AD  
3   9.385932  9.723774  10.623113  8.570374  8.203513     AD  
4   9.123317  9.519577  10.105397  8.123388  7.868757     AD  

[5 rows x 431 columns]

### Data Preprocessing

In [ ]:
# Remove the ID column from the dataset
ad_data = ad_data.drop(columns=['ID'])

# Check for NaN values in the data
nan_values = ad_data.isnull().sum()

# Display columns with NaN values, if any
nan_columns = nan_values[nan_values > 0]

if nan_columns.empty:
    print("There are no NaN values in the data.")
else:
    print("Columns with NaN values:\n", nan_columns)


# Separate the feature columns and label column
X = ad_data.iloc[:, :-1]  # Features columns (all except the last one)
y = ad_data.iloc[:, -1]   # Label column (last one)


There are no NaN values in the data.


### Split the Data for Training and Testing

In [ ]:
# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Train the Logistic Regression Model

In [ ]:
# Initialize the Logistic Regression model
log_reg = LogisticRegression(max_iter=1000, random_state=42)  # Increasing max_iter to ensure convergence

# Fit the model to the training data
log_reg.fit(X_train, y_train)



LogisticRegression(max_iter=1000, random_state=42)

### Make Predictions and Evaluate the Model

In [ ]:
# Make predictions on the test set
y_pred = log_reg.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 87.88%
Classification Report:
              precision    recall  f1-score   support

          AD       0.94      0.83      0.88        18
         CTL       0.82      0.93      0.88        15

    accuracy                           0.88        33
   macro avg       0.88      0.88      0.88        33
weighted avg       0.89      0.88      0.88        33

Confusion Matrix:
[[15  3]
 [ 1 14]]


### Train Support Vector Machine

In [ ]:
# SVM with Linear Kernel
linear_svm = SVC(kernel='linear', C=1.0, random_state=42)

# Fit the linear SVM model to the training data
linear_svm.fit(X_train, y_train)

SVC(kernel='linear', random_state=42)

In [ ]:
# Make predictions with the linear SVM model
y_pred_linear = linear_svm.predict(X_test)

# Evaluate the linear SVM model
accuracy_linear = accuracy_score(y_test, y_pred_linear)
print(f"Linear Kernel Accuracy: {accuracy_linear * 100:.2f}%")

# Print classification report for the linear kernel
print("Linear Kernel Classification Report:")
print(classification_report(y_test, y_pred_linear))

# Confusion matrix for linear kernel
print("Linear Kernel Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_linear))


Linear Kernel Accuracy: 84.85%
Linear Kernel Classification Report:
              precision    recall  f1-score   support

          AD       0.93      0.78      0.85        18
         CTL       0.78      0.93      0.85        15

    accuracy                           0.85        33
   macro avg       0.86      0.86      0.85        33
weighted avg       0.86      0.85      0.85        33

Linear Kernel Confusion Matrix:
[[14  4]
 [ 1 14]]


In [ ]:
rbf_svm = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)

# Fit the RBF SVM model to the training data
rbf_svm.fit(X_train, y_train)


SVC(random_state=42)

In [ ]:
# Make predictions with the RBF SVM model
y_pred_rbf = rbf_svm.predict(X_test)

# Evaluate the RBF SVM model
accuracy_rbf = accuracy_score(y_test, y_pred_rbf)
print(f"RBF Kernel Accuracy: {accuracy_rbf * 100:.2f}%")

# Print classification report for the RBF kernel
print("RBF Kernel Classification Report:")
print(classification_report(y_test, y_pred_rbf))

# Confusion matrix for RBF kernel
print("RBF Kernel Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rbf))

RBF Kernel Accuracy: 72.73%
RBF Kernel Classification Report:
              precision    recall  f1-score   support

          AD       0.76      0.72      0.74        18
         CTL       0.69      0.73      0.71        15

    accuracy                           0.73        33
   macro avg       0.73      0.73      0.73        33
weighted avg       0.73      0.73      0.73        33

RBF Kernel Confusion Matrix:
[[13  5]
 [ 4 11]]


In [ ]:
# Initialize the KNN classifier with K=3
knn = KNeighborsClassifier(n_neighbors=3)

# Fit the model to the training data
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
# Make predictions on the test set
y_pred = knn.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 75.76%
Classification Report:
              precision    recall  f1-score   support

          AD       0.86      0.67      0.75        18
         CTL       0.68      0.87      0.76        15

    accuracy                           0.76        33
   macro avg       0.77      0.77      0.76        33
weighted avg       0.78      0.76      0.76        33

Confusion Matrix:
[[12  6]
 [ 2 13]]


In [ ]:
# Initialize the Decision Tree classifier
decision_tree = DecisionTreeClassifier(criterion='gini', max_depth=5, random_state=42)

# Fit the model to the training data
decision_tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [ ]:
# Make predictions on the test set
y_pred = decision_tree.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 63.64%
Classification Report:
              precision    recall  f1-score   support

          AD       0.71      0.56      0.62        18
         CTL       0.58      0.73      0.65        15

    accuracy                           0.64        33
   macro avg       0.65      0.64      0.64        33
weighted avg       0.65      0.64      0.64        33

Confusion Matrix:
[[10  8]
 [ 4 11]]


In [ ]:
# Initialize the Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)

# Fit the model to the training data
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
# Make predictions on the test set
y_pred = rf_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 84.85%
Classification Report:
              precision    recall  f1-score   support

          AD       0.88      0.83      0.86        18
         CTL       0.81      0.87      0.84        15

    accuracy                           0.85        33
   macro avg       0.85      0.85      0.85        33
weighted avg       0.85      0.85      0.85        33

Confusion Matrix:
[[15  3]
 [ 2 13]]


# PCA

In [ ]:
# Standardize the features (important before applying PCA)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Apply PCA for dimensionality reduction
pca = PCA(n_components=20)  # Choose the number of components or variance to retain (0.95 means 95% variance)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

# Check how many components were selected based on 95% variance
print(f"Number of components selected: {pca.n_components_}")

Number of components selected: 20


In [ ]:
# Apply Logistic Regression on the transformed data (after PCA)
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train_pca, y_train)

# Make predictions on the test set
y_pred = log_reg.predict(X_test_pca)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 78.79%
Classification Report:
              precision    recall  f1-score   support

          AD       0.87      0.72      0.79        18
         CTL       0.72      0.87      0.79        15

    accuracy                           0.79        33
   macro avg       0.79      0.79      0.79        33
weighted avg       0.80      0.79      0.79        33

Confusion Matrix:
[[13  5]
 [ 2 13]]
